### ISSUE TITLE
Compiler panic on nested array destructuring in function parameter

### ISSUE THREAD

**Issue by cherryblossom000** [typst/typst#1213]
### Description

```typst
#let f = (((x, y), z)) => {}
#f(((1, 2), 3))
```

Attempting to compile this code using Typst v0.3.0 results in

```none
thread 'main' panicked at 'internal error: entered unreachable code', src/eval/mod.rs:1357:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In the web app the error ‘The compiler crashed.’ appears.

The code that causes the panic:

https://github.com/typst/typst/blob/4b17c3f5c65a3ec87719d3c39d270767140e3767/src/eval/mod.rs#L1395-L1404

### Reproduction URL

https://typst.app/project/ppwfVCj4ZK1eRb47e8Q0B6

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Cc @Marmare314

**Comment by PgBiel** [comment]
Stack trace (on 4b17c3f5c65a3ec87719d3c39d270767140e3767):

```
thread 'main' panicked at 'internal error: entered unreachable code', src/eval/mod.rs:1402:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
   3: typst::eval::<impl typst::syntax::ast::Pattern>::define::{{closure}}
             at (...)/typst/src/eval/mod.rs:1402:18
   4: typst::eval::<impl typst::syntax::ast::Pattern>::destruct_array
             at (...)/typst/src/eval/mod.rs:1289:21
   5: typst::eval::<impl typst::syntax::ast::Pattern>::apply
             at (...)/typst/src/eval/mod.rs:1388:40
   6: typst::eval::<impl typst::syntax::ast::Pattern>::define
             at (...)/typst/src/eval/mod.rs:1397:9
   7: typst::eval::func::Closure::call::{{closure}}
             at (...)/typst/src/eval/func.rs:374:25
   8: comemo::cache::memoized::{{closure}}
             at ~/.cargo/git/checkouts/comemo-3f14ec85877504be/0c141bb/src/cache.rs:65:22
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/local.rs:446:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/local.rs:422:9
  11: comemo::cache::memoized
             at ~/.cargo/git/checkouts/comemo-3f14ec85877504be/0c141bb/src/cache.rs:36:5
  12: typst::eval::func::Closure::call
             at (...)/typst/src/eval/func.rs:322:5
  13: typst::eval::func::Func::call_vm
             at (...)/typst/src/eval/func.rs:102:17
  14: <typst::syntax::ast::FuncCall as typst::eval::Eval>::eval::{{closure}}
             at (...)/typst/src/eval/mod.rs:1163:20
  15: stacker::maybe_grow
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  16: <typst::syntax::ast::FuncCall as typst::eval::Eval>::eval
             at (...)/typst/src/eval/mod.rs:1170:9
  17: <typst::syntax::ast::Expr as typst::eval::Eval>::eval
             at (...)/typst/src/eval/mod.rs:473:34
  18: typst::eval::eval_markup
             at (...)/typst/src/eval/mod.rs:399:27
  19: <typst::syntax::ast::Markup as typst::eval::Eval>::eval
             at (...)/typst/src/eval/mod.rs:368:9
  20: typst::eval::eval::{{closure}}
             at (...)/typst/src/eval/mod.rs:105:18
  21: comemo::cache::memoized::{{closure}}
             at ~/.cargo/git/checkouts/comemo-3f14ec85877504be/0c141bb/src/cache.rs:65:22
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/local.rs:446:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/local.rs:422:9
  24: comemo::cache::memoized
             at ~/.cargo/git/checkouts/comemo-3f14ec85877504be/0c141bb/src/cache.rs:36:5
  25: typst::eval::eval
             at (...)/typst/src/eval/mod.rs:66:1
  26: typst::compile
             at (...)/typst/src/lib.rs:78:18
  27: typst::compile_once
             at (...)/typst/cli/src/main.rs:246:11
  28: typst::compile
             at (...)/typst/cli/src/main.rs:175:18
  29: typst::main
             at (...)/typst/cli/src/main.rs:133:13
  30: core::ops::function::FnOnce::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by PgBiel** [comment]
Seems like it's expecting the `(x, y)` part to be a variable name (ident), but it's receiving the whole array (it's not properly entering nested arrays).

**Comment by Marmare314** [comment]
Yes, I think it's because in `validate_pattern` no error is thrown on `SyntaxKind::Array` and `SyntaxKind::Dict`.

**Comment by Marmare314** [comment]
My previous comment (and the code for that matter) was based on the assumption that nested patterns are not allowed. So fixing this error in that case is easy. However I think that nested patterns are really useful, but I'm not sure yet how difficult it would be to implement them.

**Comment by PgBiel** [comment]
Yeah, I guess we could add an error for now instead of crashing, and later implement this feature (as it'd certainly be very useful to have nested patterns)
