### ISSUE TITLE
Compiler panic on minimal layout change

### ISSUE THREAD

**Issue by thinety** [typst/typst#1216]
### Description

The following code compiles fine:
````typst
#show raw.where(block: true): block.with(fill: luma(230), radius: 4pt)
#v(63em)
```
```
````

But changing the vertical spacing
````typst
#show raw.where(block: true): block.with(fill: luma(230), radius: 4pt)
#v(64em)
```
```
````
causes `typst 0.3.0 (b1e0de00)` to panic:
```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/cmp.rs:857:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Rerunning with `RUST_BACKTRACE=full` gives no useful information.

The relevant code from rustc is [here](https://github.com/rust-lang/rust/blob/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/cmp.rs#L851-L865):
```rust
    fn clamp(self, min: Self, max: Self) -> Self
    where
        Self: Sized,
        Self: ~const Destruct,
        Self: ~const PartialOrd,
    {
        assert!(min <= max);
        if self < min {
            min
        } else if self > max {
            max
        } else {
            self
        }
    }
```

`Ord::clamp` is used a few times throughout the codebase, but I am not really sure who's the culprit. Maybe this?

https://github.com/typst/typst/blob/1fa56a317c8d8da76546e6b5e19b279d84380837/src/geom/rounded.rs#L66-L67

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
> Rerunning with `RUST_BACKTRACE=full` gives no useful information.

This is likely because you're using the optimized binary (compiled in release mode). Compiling in debug mode is needed to get useful info here.

**Comment by thinety** [comment]
```sh
$ ./target/debug/typst --version
typst 0.3.0 (b1e0de00)
```

Backtrace now is:
```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/cmp.rs:840:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:117:5
   3: core::cmp::Ord::clamp
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/cmp.rs:840:9
   4: typst::geom::rounded::stroke_segments
             at ./src/geom/rounded.rs:66:13
   5: typst::geom::rounded::fill_geometry
             at ./src/geom/rounded.rs:38:25
   6: typst::geom::rounded::rounded_rect
             at ./src/geom/rounded.rs:15:23
   7: typst::doc::Frame::fill_and_stroke
             at ./src/doc.rs:313:13
   8: <typst_library::layout::container::BlockElem as typst_library::layout::Layout>::layout
             at ./library/src/layout/container.rs:427:17
   9: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ./library/src/layout/mod.rs:152:13
  10: comemo::cache::memoized::{{closure}}
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:55:22
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:270:16
  12: std::thread::local::LocalKey<T>::with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:246:9
  13: comemo::cache::memoized
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:23:11
  14: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ./library/src/layout/mod.rs:139:9
  15: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ./library/src/layout/mod.rs:160:9
  16: typst_library::layout::flow::FlowLayouter::layout_multiple
             at ./library/src/layout/flow.rs:230:24
  17: <typst_library::layout::flow::FlowElem as typst_library::layout::Layout>::layout
             at ./library/src/layout/flow.rs:62:17
  18: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached::{{closure}}
             at ./library/src/layout/mod.rs:152:13
  19: comemo::cache::memoized::{{closure}}
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:55:22
  20: std::thread::local::LocalKey<T>::try_with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:270:16
  21: std::thread::local::LocalKey<T>::with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:246:9
  22: comemo::cache::memoized
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:23:11
  23: <typst::model::content::Content as typst_library::layout::Layout>::layout::cached
             at ./library/src/layout/mod.rs:139:9
  24: <typst::model::content::Content as typst_library::layout::Layout>::layout
             at ./library/src/layout/mod.rs:160:9
  25: typst_library::layout::page::PageElem::layout
             at ./library/src/layout/page.rs:321:28
  26: <typst_library::meta::document::DocumentElem as typst_library::layout::LayoutRoot>::layout_root
             at ./library/src/meta/document.rs:62:32
  27: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached::{{closure}}
             at ./library/src/layout/mod.rs:85:13
  28: comemo::cache::memoized::{{closure}}
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:55:22
  29: std::thread::local::LocalKey<T>::try_with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:270:16
  30: std::thread::local::LocalKey<T>::with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:246:9
  31: comemo::cache::memoized
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:23:11
  32: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::cached
             at ./library/src/layout/mod.rs:73:9
  33: <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root
             at ./library/src/layout/mod.rs:93:9
  34: typst_library::items::{{closure}}
             at ./library/src/lib.rs:186:42
  35: core::ops::function::FnOnce::call_once
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
  36: typst::model::typeset::{{closure}}
             at ./src/model/mod.rs:54:20
  37: comemo::cache::memoized::{{closure}}
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:55:22
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:270:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:246:9
  40: comemo::cache::memoized
             at /home/thinety/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.2.2/src/cache.rs:23:11
  41: typst::model::typeset
             at ./src/model/mod.rs:25:1
  42: typst::compile
             at ./src/lib.rs:78:5
  43: typst::compile_once
             at ./cli/src/main.rs:246:11
  44: typst::compile
             at ./cli/src/main.rs:175:18
  45: typst::main
             at ./cli/src/main.rs:133:13
  46: core::ops::function::FnOnce::call_once
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

So the offending call to `Ord::clamp` really is here:
https://github.com/typst/typst/blob/1fa56a317c8d8da76546e6b5e19b279d84380837/src/geom/rounded.rs#L66
