### ISSUE TITLE
Compiler crash after printing second compilation status message

### ISSUE THREAD

**Issue by ThomasFrans** [typst/typst#1298]
### Description

With any input, the compiler crashes after recompiling the project. The issue seems to happen when getting the local system time in the `status()` function under `cli/src/main.rs:362`. There is a closed issue on the `time` crate that mentions the `now_local()` method on `OffsetDateTime` doesn't work in multithreaded programs on POSIX systems.

I was testing the new time/date functionality on nightly, and this issue seems to be introduced by the PR that added it (#435).

## Typst input file (`presentation.typ`):
```
Hello world!
```

## Compiler command
```
typst watch presentation.typ
```

## Compiler panic message
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndeterminateOffset', cli/src/main.rs:362:50
```

## Backtrace (after running from source)
```
  13:     0x555ebbf05042 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:     0x555ebb05d2b3 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:     0x555ebb05d763 - core::result::unwrap_failed::hdc73d4affce1d414
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
  16:     0x555ebb18322a - core::result::Result<T,E>::unwrap::h3a3e3336939912ae
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1112:23
  17:     0x555ebb0d9d44 - typst::status::h20c1c1c3b034153e
                               at /home/thomas/Documents/development/rust/typst.git/fix-timedate-panic/cli/src/main.rs:362:16
  18:     0x555ebb0d7fb5 - typst::compile_once::hab2ea5840caa7cb8
                               at /home/thomas/Documents/development/rust/typst.git/fix-timedate-panic/cli/src/main.rs:289:5
  19:     0x555ebb0d3c95 - typst::compile::hd28309cb2d766a9e
                               at /home/thomas/Documents/development/rust/typst.git/fix-timedate-panic/cli/src/main.rs:268:22
  20:     0x555ebb0d20b0 - typst::main::hee363b601a3d4514
                               at /home/thomas/Documents/development/rust/typst.git/fix-timedate-panic/cli/src/main.rs:59:13
  21:     0x555ebb0f044b - core::ops::function::FnOnce::call_once::h6493bb9fb401d8ae
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  22:     0x555ebb07680e - std::sys_common::backtrace::__rust_begin_short_backtrace::h21509d5659ab9562
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:121:18
  23:     0x555ebb11bdd1 - std::rt::lang_start::{{closure}}::hda3ffb6f936b73f5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:166:18
  24:     0x555ebbef9bac - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h699977d052768608
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:287:13
  25:     0x555ebbef9bac - std::panicking::try::do_call::h4e121e623c70f903
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  26:     0x555ebbef9bac - std::panicking::try::hf9d919e062bc178a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  27:     0x555ebbef9bac - std::panic::catch_unwind::h7a7b12272684cb97
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  28:     0x555ebbef9bac - std::rt::lang_start_internal::{{closure}}::hd96b0eb4844b8762
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:48
  29:     0x555ebbef9bac - std::panicking::try::do_call::h1af1f88f4f92a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  30:     0x555ebbef9bac - std::panicking::try::hf20d7abea7f0f097
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  31:     0x555ebbef9bac - std::panic::catch_unwind::hb0e084c3a9c042e4
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  32:     0x555ebbef9bac - std::rt::lang_start_internal::hca9d5c7277f5b67c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:20
  33:     0x555ebb11bdaa - std::rt::lang_start::hdac63ba8237071fb
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:165:17
  34:     0x555ebb0de9ce - main
  35:     0x7fb7d1142850 - <unknown>
  36:     0x7fb7d114290a - __libc_start_main
  37:     0x555ebb05d945 - _start
  38:                0x0 - <unknown>
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Can reproduce; seems like a somewhat critical bug.

**Comment by ThomasFrans** [comment]
No. I was pretty surprised this made it into the main branch. I thought I just screwed something up when using Typst. It's not that subtle of a bug :smile:

**Comment by LaurenzV** [comment]
Yeah, sorry, we switched to a new crate for getting the current time, and it seems like this broke `typst watch` :/ I actually even tried this on my computer because I was afraid this would break something, but it worked fine for me. I will see if I can revert this.

**Comment by LaurenzV** [comment]
@ThomasFrans If you want you can try out the branch in the PR above, it should fix the issue. Thanks for catching this early.

**Comment by ThomasFrans** [comment]
I don't have the time to test it right now. I'm sorry :slightly_frowning_face: If it really needs to be tested, I'll do it next week. Thank you for fixing this.

**Comment by LaurenzV** [comment]
No worries, someone else already tested it and it should be fine. :)
