### ISSUE TITLE
typst-cli watch panic: thread 'main' panicked at 'span does not point into this source file'

### ISSUE THREAD

**Issue by Myriad-Dreamin** [typst/typst#2035]
### Description

One should try following action repeatedly to trigger this bug, because it is not quite stable. To reproduce it:

+ randomly edit the line in file https://github.com/Myriad-Dreamin/typst-book/blob/5ff6fa4e14c2dbc6563a5eb1e71addb1fac1d74a/contrib/typst/i18n.typ

  ```js
  assert(flow_nodes.len() >= 1, message: "no id to translate")
  ```

Reproduce state:
+ I can reproduce it by [v0.7.0/typst-x86_64-pc-windows-msvc/typst.exe](https://github.com/typst/typst/releases/download/v0.7.0/typst-x86_64-pc-windows-msvc.zip)
+ I can reproduce it on [webapp](https://typst.app/project/p-OzkGGPmECN66pwSjUOrx#)
+ I can reproduce it by typst preview plugin.

Related issue: https://github.com/Enter-tainer/typst-preview/issues/105

The output of [v0.7.0/typst-x86_64-pc-windows-msvc/typst.exe](https://github.com/typst/typst/releases/download/v0.7.0/typst-x86_64-pc-windows-msvc.zip)

```
watching .\github-pages\docs\locale\zh_CN\format\book-meta.typ
writing to .\github-pages\docs\locale\zh_CN\format\book-meta.pdf

[12:45:55] compiling ...

thread 'main' panicked at 'span does not point into this source file', D:\a\typst\typst\crates\typst\src\lib.rs:102:1
stack backtrace:
   0:     0x7ff6bf85a041 - <unknown>
   1:     0x7ff6bf51deab - <unknown>
   2:     0x7ff6bf855249 - <unknown>
   3:     0x7ff6bf859deb - <unknown>
   4:     0x7ff6bf85d5d9 - <unknown>
   5:     0x7ff6bf85d2b2 - <unknown>
   6:     0x7ff6bf85dabe - <unknown>
   7:     0x7ff6bf85d9b5 - <unknown>
   8:     0x7ff6bf85b889 - <unknown>
   9:     0x7ff6bf85d6a4 - <unknown>
  10:     0x7ff6bff8bc25 - <unknown>
  11:     0x7ff6bff8bbe2 - <unknown>
  12:     0x7ff6bfe6c329 - <unknown>
  13:     0x7ff6bfb6f924 - <unknown>
  14:     0x7ff6bfcbbc45 - <unknown>
  15:     0x7ff6bfd1997d - <unknown>
  16:     0x7ff6bfe0e56a - <unknown>
  17:     0x7ff6bfe0cf6f - <unknown>
  18:     0x7ff6bfc02206 - <unknown>
  19:     0x7ff6bfa69f28 - <unknown>
  20:     0x7ff6bfaf21f9 - <unknown>
  21:     0x7ff6bfae167c - <unknown>
  22:     0x7ff6bfaf1da9 - <unknown>
  23:     0x7ff6bfae167c - <unknown>
  24:     0x7ff6bfa7f0c3 - <unknown>
  25:     0x7ff6bfaec39c - <unknown>
  26:     0x7ff6bfae14db - <unknown>
  27:     0x7ff6bfa21dbe - <unknown>
  28:     0x7ff6bfa640bc - <unknown>
  29:     0x7ff6bfde8c69 - <unknown>
  30:     0x7ff6bfac4937 - <unknown>
  31:     0x7ff6bfce3b79 - <unknown>
  32:     0x7ff6bfce3c5f - <unknown>
  33:     0x7ff6bfce3fd9 - <unknown>
  34:     0x7ff6bfce3bd5 - <unknown>
  35:     0x7ff6bfce3c5f - <unknown>
  36:     0x7ff6bfce3fd9 - <unknown>
  37:     0x7ff6bfce3c5f - <unknown>
  38:     0x7ff6bfd9ace8 - <unknown>
  39:     0x7ff6bfc1dc40 - <unknown>
  40:     0x7ff6bfb38cf8 - <unknown>
  41:     0x7ff6bfb3b6a8 - <unknown>
  42:     0x7ff6bfbb1c9b - <unknown>
  43:     0x7ff6bfb9bccc - <unknown>
  44:     0x7ff6bfb556c6 - <unknown>
  45:     0x7ff6bf84e032 - <unknown>
  46:     0x7ff6bfbbc24c - <unknown>
  47:     0x7ff6bff89d2c - <unknown>
  48:     0x7ff9725126ad - BaseThreadInitThunk
  49:     0x7ff9730eaa68 - RtlUserThreadStart
```

The output of the [webapp](https://typst.app/project/p-OzkGGPmECN66pwSjUOrx#):

![image](https://github.com/typst/typst/assets/35292584/e7727cd4-b6f6-4e1e-91de-94001ffe3bb1)

The output of `typst-preview.exe` (which uses typst compiler):

```
[2023-08-29T03:38:06Z INFO  typst_ts_compiler::service::diag] \github-pages\docs\locale\zh_CN\format\book-meta.typ: compiling ...
thread '<unnamed>' panicked at 'span does not point into this source file', C:\Users\[hidden]\.cargo\git\checkouts\typst-15b90983aa0184a9\706d64f\crates\typst\src\lib.rs:102:1
stack backtrace:
   0:     0x7ff63deda19c - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff63df0244b - core::fmt::rt::Argument::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\rt.rs:138
   2:     0x7ff63df0244b - core::fmt::write
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\mod.rs:1094
   3:     0x7ff63ded4a6f - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\io\mod.rs:1714
   4:     0x7ff63ded9f4b - std::sys_common::backtrace::_print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff63ded9f4b - std::sys_common::backtrace::print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff63dedca1a - std::panicking::default_hook::closure$1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:269
   7:     0x7ff63dedc66f - std::panicking::default_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:288
   8:     0x7ff63dedd0ce - std::panicking::rust_panic_with_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:705
   9:     0x7ff63dedcfbd - std::panicking::begin_panic_handler::closure$0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:597
  10:     0x7ff63dedade9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:151
  11:     0x7ff63dedccc0 - std::panicking::begin_panic_handler
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
  12:     0x7ff63df4eb35 - core::panicking::panic_fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
  13:     0x7ff63df4eaf2 - core::panicking::panic_display
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:150
  14:     0x7ff63df4eaf2 - core::panicking::panic_str
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:134
  15:     0x7ff63df4eaf2 - core::option::expect_failed
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\option.rs:1952
  16:     0x7ff63dcd0db2 - typst_syntax::source::Source::range::h772764d002cace7b
  17:     0x7ff63d2af6c8 - typst::World::range::hd4986400e0d5b667
  18:     0x7ff63dbab5b5 - comemo::cache::memoized::{{closure}}::h9f8a4a98177ad8ad
  19:     0x7ff63dba43ec - comemo::cache::memoized::{{closure}}::h9f8a4a98177ad8ad
  20:     0x7ff63db99de9 - comemo::cache::memoized::h75291853097e0632
  21:     0x7ff63db52fff - typst::eval::func::Func::call_vm::hd5941fd5c92d433d
  22:     0x7ff63d474a0d - typst::model::Vt::delayed::hba39e1e20d9d999b
  23:     0x7ff63d5f4839 - <typst_library::meta::context::LocateElem as typst::model::realize::Show>::show::hd8b31ecaa459a231
  24:     0x7ff63daed4ce - typst::model::realize::realize::h86036e8219255b5b
  25:     0x7ff63d5ea290 - typst_library::layout::define::h69e9238461ecef7f
  26:     0x7ff63d5ea437 - typst_library::layout::define::h69e9238461ecef7f
  27:     0x7ff63d5ea4b0 - typst_library::layout::define::h69e9238461ecef7f
  28:     0x7ff63d5ea3c6 - typst_library::layout::define::h69e9238461ecef7f
  29:     0x7ff63d5ea437 - typst_library::layout::define::h69e9238461ecef7f
  30:     0x7ff63d5ea4b0 - typst_library::layout::define::h69e9238461ecef7f
  31:     0x7ff63d5ea437 - typst_library::layout::define::h69e9238461ecef7f
  32:     0x7ff63d5f27ab - typst_library::layout::realize_root::h25fd89773881bde4
  33:     0x7ff63d603398 - comemo::cache::memoized::h85b99e09fb39f8bc
  34:     0x7ff63d43aaed - <typst::model::content::Content as typst_library::layout::LayoutRoot>::layout_root::hbde5354b8ddd0d43
  35:     0x7ff63d3f2e50 - http::uri::scheme::Scheme::empty::h6e81c139f1cb2b86
  36:     0x7ff63db94d44 - comemo::cache::memoized::h139c00ab40234037
  37:     0x7ff63dadd6a4 - typst::model::typeset::h8e037222030d0fa1
  38:     0x7ff63dad5262 - typst::compile::h2a9993dd28be9b32
  39:     0x7ff63d2af8c5 - <C as typst_ts_compiler::service::DiagObserver>::with_compile_diag::h4859ad321f3293b0
  40:     0x7ff63d28d0eb - typst_preview::actor::typst::TypstActor::new::h88ebe99ffbaf6a36
  41:     0x7ff63d27d0e9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8e70adff2028f5ed
  42:     0x7ff63d27ef5f - core::fmt::Write::write_fmt::h4d1472d0999b2b2a
  43:     0x7ff63deeadac - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys\windows\thread.rs:57
  44:     0x7ff9725126ad - BaseThreadInitThunk
  45:     0x7ff9730eaa68 - RtlUserThreadStart
```

Need more investigation to locate the reason why it panics.

### Reproduction URL

https://typst.app/project/rSpwBj23HTcKvYkOPCG3bE

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Possibly related to https://github.com/nvarner/typst-lsp/issues/241

**Comment by laurmaedje** [comment]
I think I have an idea what's going on here: The `range` method is comemo-tracked (even though it doesn't need to be) and it panics on wrong spans instead of returning an option.

What's probably happening is that comemo tries to validate some cached results against a new world. But in that world, the span is meaningless and panics. I will push a fix soon, switching to returning options and maybe moving the range function into an extension trait.

This will also fix CLI panics for detached spans. The CLI will rather unhelpfully print the error without any location information then, buts that's better than panicking. Errors on detached spans are very rare anyway, just unfortunately not prevented on the type-system level.

It is very possible that this is also the problem in Typst LSP.

**Comment by laurmaedje** [comment]
Should be fixed by https://github.com/typst/typst/commit/a71a2057f286677b5bf2e064fea05024aeca0dd2
