### ISSUE TITLE
Empty `typ` raw block causes panic (0.11 regression)

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#3601]
### Description

Discovered by @Andrew15-5 

To reproduce, write

````
```typ
```
````

in a 0.11-rc1 document, which panics at this line (trying to access `lines[i]`):

https://github.com/typst/typst/blob/a2d097686f01b2834f4a9b313bd9c1c692210479/crates/typst/src/text/raw.rs#L358

As a "one-liner" (sort of), you can write the following with the CLI:

````bash
RUST_BACKTRACE=full target/debug/typst compile - a.pdf <<HEREDOC
$(echo '```')typ
$(echo '```')
HEREDOC
````

Seems to be related to #3257 (cc @Myriad-Dreamin @laurmaedje).

The panic does not occur with raw blocks of other languages (e.g. `rs`), just `typ`, `typst` and `typc`.

<details><summary>Full panic backtrace</summary>

<p>

```
thread 'main' panicked at crates/typst/src/text/raw.rs:358:61:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x55fbf321a996 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55fbf321a996 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fbf321a996 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55fbf321a996 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fbf324cc20 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55fbf324cc20 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55fbf3216f3f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55fbf321a774 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fbf321a774 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fbf321c077 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55fbf321bdd9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55fbf321c508 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55fbf321c3e2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55fbf321ae96 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55fbf321c140 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55fbf1adfa25 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55fbf1adfc62 - core::panicking::panic_bounds_check::h8331054858f0bf20
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:208:5
  17:     0x55fbf27142a3 - typst::text::raw::<impl typst::foundations::content::Packed<typst::text::raw::RawElem>>::highlight::{{closure}}::{{closure}}::hd992c38ed137c984
                               at typst/crates/typst/src/text/raw.rs:358:61
  18:     0x55fbf22500eb - typst::text::raw::ThemedHighlighter::highlight_inner::h466a25b168cfd4bf
                               at typst/crates/typst/src/text/raw.rs:657:40
  19:     0x55fbf224f923 - typst::text::raw::ThemedHighlighter::highlight::h8882b9a4d7ee7b26
                               at typst/crates/typst/src/text/raw.rs:625:9
  20:     0x55fbf2713c87 - typst::text::raw::<impl typst::foundations::content::Packed<typst::text::raw::RawElem>>::highlight::{{closure}}::hd7ab5e3f9a5c2008
                               at typst/crates/typst/src/text/raw.rs:348:13
  21:     0x55fbf2484651 - comemo::cache::memoized::hfa32ab2e409e9c6b
                               at ~/.var/app/com.jetbrains.RustRover/data/cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
  22:     0x55fbf24ee1a5 - typst::text::raw::<impl typst::foundations::content::Packed<typst::text::raw::RawElem>>::highlight::hd8e2fb9d3fa04037
                               at typst/crates/typst/src/text/raw.rs:300:5
  23:     0x55fbf24c21f9 - typst::text::raw::<impl typst::foundations::element::Synthesize for typst::foundations::content::Packed<typst::text::raw::RawElem>>::synthesize::h8b3ed1baafe94768
                               at typst/crates/typst/src/text/raw.rs:293:19
  24:     0x55fbf27f5efe - typst::realize::process::verdict::h04ec3867122ffb3b
                               at typst/crates/typst/src/realize/process.rs:108:9
  25:     0x55fbf27f55e5 - typst::realize::process::process::hac2b928ad12ea310
                               at typst/crates/typst/src/realize/process.rs:49:53
  26:     0x55fbf281c5cd - typst::realize::Builder::accept::h4ac51c48644e86c0
                               at typst/crates/typst/src/realize/mod.rs:112:33
  27:     0x55fbf281ce92 - typst::realize::Builder::accept::h4ac51c48644e86c0
                               at typst/crates/typst/src/realize/mod.rs:131:17
  28:     0x55fbf2821678 - typst::realize::realize_root::hb4552f01d7a59316
                               at typst/crates/typst/src/realize/mod.rs:42:5
  29:     0x55fbf1f49c29 - <typst::foundations::content::Content as typst::layout::LayoutRoot>::layout_root::cached::{{closure}}::h6710facc885e6d40
                               at typst/crates/typst/src/layout/mod.rs:199:38
  30:     0x55fbf2477006 - comemo::cache::memoized::h0c5809dce64b5b2b
                               at ~/.var/app/com.jetbrains.RustRover/data/cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
  31:     0x55fbf243a56c - <typst::foundations::content::Content as typst::layout::LayoutRoot>::layout_root::cached::hb2d499e3f8021db6
                               at typst/crates/typst/src/layout/mod.rs:180:9
  32:     0x55fbf24b8f8b - <typst::foundations::content::Content as typst::layout::LayoutRoot>::layout_root::hf821df619b3beb63
                               at typst/crates/typst/src/layout/mod.rs:203:9
  33:     0x55fbf2898b6f - typst::typeset::hb5a42c5f92ddafe1
                               at typst/crates/typst/src/lib.rs:141:20
  34:     0x55fbf289b1e4 - typst::compile::h47316f52308de0e6
                               at typst/crates/typst/src/lib.rs:103:5
  35:     0x55fbf1bcec82 - typst::compile::compile_once::h04d8926eba2c2f00
                               at typst/crates/typst-cli/src/compile.rs:100:18
  36:     0x55fbf1bbd73f - typst::compile::compile::{{closure}}::h04ca455818e71884
                               at typst/crates/typst-cli/src/compile.rs:68:38
  37:     0x55fbf1b98241 - typst::timings::Timer::record::h98067cc0146ad31a
                               at typst/crates/typst-cli/src/timings.rs:48:23
  38:     0x55fbf1bcce1c - typst::compile::compile::h32690158807a23b9
                               at typst/crates/typst-cli/src/compile.rs:68:5
  39:     0x55fbf1b971f4 - typst::main::hd9916c0db915c801
                               at typst/crates/typst-cli/src/main.rs:41:38
  40:     0x55fbf1ba069b - core::ops::function::FnOnce::call_once::h606ac727b73790aa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  41:     0x55fbf1b2556e - std::sys_common::backtrace::__rust_begin_short_backtrace::h77ac2b86431a4331
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  42:     0x55fbf1b764c1 - std::rt::lang_start::{{closure}}::h5bbda344909ee9dc
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  43:     0x55fbf320dcb1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  44:     0x55fbf320dcb1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  45:     0x55fbf320dcb1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  46:     0x55fbf320dcb1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  47:     0x55fbf320dcb1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  48:     0x55fbf320dcb1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  49:     0x55fbf320dcb1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  50:     0x55fbf320dcb1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  51:     0x55fbf320dcb1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  52:     0x55fbf1b7649a - std::rt::lang_start::h78e59b1212756696
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  53:     0x55fbf1b9787e - main
  54:     0x7f23e183b08a - <unknown>
  55:     0x7f23e183b14b - __libc_start_main
  56:     0x55fbf1ae0365 - _start
                               at /buildstream-build/csu/../sysdeps/x86_64/start.S:115
  57:                0x0 - <unknown>```

</p>
</details>


### Reproduction URL

_No response_

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Andrew15-5** [comment]
> As a "one-liner" (sort of), you can write the following with the CLI:
> 
> ```shell
> RUST_BACKTRACE=full cargo run -- compile - a.pdf <<HEREDOC
> $(echo '```')typ
> $(echo '```')
> HEREDOC
> ```

````sh
printf '```typ\n```' | RUST_BACKTRACE=full cargo run -- compile - a.pdf
````

> The panic does not occur with raw blocks of other languages (e.g. `rs`), just `typ`, `typst` and `typc`.

It also doesn't occur when no language is specified.
