### ISSUE TITLE
Test failures with rustc 1.83.0-nightly (94885bc69 2024-09-01)

### ISSUE THREAD

**Issue by bluebear94** [typst/typst#4877]
### Description

Some of the integration tests fail in the latest nightly version of Rust (`rustc 1.83.0-nightly (94885bc69 2024-09-01)`):

```
💨 708 / 2224
' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
bounded paragraph layout is incomplete
💨 710 / 2224
thread '<unnamed>' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
💨 713 / 2224
❌ justify-no-leading-spaces (tests/suite/layout/inline/justify.typ:76) panicked
💨 714 / 2224
❌ justify (tests/suite/layout/inline/justify.typ:2) panicked
:
bounded paragraph layout is incomplete
💨 723 / 2224
❌ issue-2419-justify-hanging-indent (tests/suite/layout/inline/justify.typ:166) panicked
💨 827 / 2224
thread '<unnamed>' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
bounded paragraph layout is incomplete
❌ justify-code-blocks (tests/suite/layout/inline/justify.typ:86) panicked
💨 1376 / 2224
thread '<unnamed>' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
bounded paragraph layout is incomplete
❌ par-hanging-indent (tests/suite/model/par.typ:68) panicked
❌ issue-4278-par-trim-before-equation (tests/suite/model/par.typ:98)
  mismatched rendering
    live      | tests/store/render/issue-4278-par-trim-before-equation.png
    ref       | tests/ref/issue-4278-par-trim-before-equation.png
💨 1847 / 2224
thread '<unnamed>' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
bounded paragraph layout is incomplete
❌ show-text-regex-character-class (tests/suite/styling/show-text.typ:63) panicked
💨 1902 / 2224
thread '<unnamed>' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
bounded paragraph layout is incomplete
❌ show-selector-where (tests/suite/styling/show.typ:197) panicked
💨 2006 / 2224
thread '<unnamed>' panicked at crates/typst/src/layout/inline/linebreak.rs:332:9:
bounded paragraph layout is incomplete
❌ issue-3191-raw-indent-shrink (tests/suite/text/raw.typ:605) panicked
2215 passed, 9 failed, 0 skipped
  pass the --update flag to update the reference images
error: test failed, to rerun pass `--test tests`
```

In contrast, all tests pass with rustc 1.80.1 and 1.81.0-beta.8.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
After some investigation, I’ve found that 2022-08-21 is unaffected by this issue, but 2022-08-22 is affected.
