### ISSUE TITLE
Compiler panic with horizontal space in header

### ISSUE THREAD

**Issue by AldanTanneo** [typst/typst#5244]
### Description

I was using a custom raw text rendering with a `show` rule that would add a small amount of horizontal spacing on each side, when I encountered a compiler panic.

Basically, after investigation, this minimal reproduction panics on typst 0.12.0:

```typst
#set par(justify: true)
#set heading(numbering: "I.")

= #h(0.3em, weak: true) test
```

Panic message:

```
thread 'main' panicked at /.../typst-0.12.0/src/layout/inline/linebreak.rs:977:35:
index out of bounds: the len is 8 but the index is 8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The panic originates with an out-of-bounds index in the `linebreak_optimized_approximate` function, specifically when getting an estimate of a widths metric: `estimates.widths.estimate(start..trimmed_end)`.

The panic will NOT occur if:
- the spacing is not set as `weak`
- there is no text after the spacing
- there is text before the spacing
- the heading has no numbering
- the paragraphs are not set to justified

<details>
<summary>Here is a relevant backtrace excerpt:</summary>

```
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/mod.rs:2912:9
   6: typst::layout::inline::linebreak::CumulativeVec<T>::get
             at /.../typst-0.12.0/src/layout/inline/linebreak.rs:977:35
   7: typst::layout::inline::linebreak::CumulativeVec<T>::estimate
             at /.../typst-0.12.0/src/layout/inline/linebreak.rs:970:9
   8: typst::layout::inline::linebreak::linebreak_optimized_approximate::{{closure}}
             at /.../typst-0.12.0/src/layout/inline/linebreak.rs:403:17
   9: typst::layout::inline::linebreak::breakpoints
             at /.../typst-0.12.0/src/layout/inline/linebreak.rs:719:9
  10: typst::layout::inline::linebreak::linebreak_optimized_approximate
```

</details>

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Logging my debugging results so far: the problem seems to be somewhere in paragraph preparation (or `collect`):

- The prepared paragraph text (`p.text`) for the heading seems to be `" N.  test"`, a string of length 9;
- Normally, the list of prepared items will have consecutive ranges such as 0-2, 2-5, ..., such that the last one must end at `text.len()`, IIUC. In this case, however, the last item ends at `8`, not `9`.
- As a consequence, these lines which compute estimates for each byte in the paragraph text by looping on the items and their ranges will not compute an estimate for the last byte (index 8), since no item appears to include that byte.
    https://github.com/typst/typst/blob/89d96c623dc882fcdbff02e201bcfb27e6bbfd2a/crates/typst-layout/src/inline/linebreak.rs#L912-L931
- Therefore, we get a panic when trying to access estimates for the last byte in the approximate optimized linebreak procedure. When iterating over breakpoints, the last breakpoint has index `9` (end of string), so we try to get an estimate for the byte right before it here (since we get an estimate for all bytes from `start`, the index of the previous breakpoint (happens to be `0` in this case, but could be any other value), to `trimmed_end` which is 9), which fails since no estimate was computed for that byte:
    https://github.com/typst/typst/blob/89d96c623dc882fcdbff02e201bcfb27e6bbfd2a/crates/typst-layout/src/inline/linebreak.rs#L395-L403

Further investigation is needed to determine why paragraph preparation is producing items with incorrect ranges.

I did notice that one of the segments - precisely between `N.` and `test` - returned by `collect()` is a `Segment::Item(Item::Text)` with a text value that appears (?) to be an empty / length 0 string but somehow has a textual len of 1, and either way the length should be 2 to match the amount of spaces in the paragraph text string. This seems to be what's messing up the range counter, generating wrong ranges for the items. But I'm not sure yet why this is happening.
