### ISSUE TITLE
Panic with block and text having negative sizes

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#5262]
### Description

0.12 regression (appears to work in 0.11.1)

Reproducer:

```typ
#set page(height: 10pt, margin: (top: 9pt))
#block(height: 100%)[]
```

Compiling with `typst c doc.typ`:
```
thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cmp.rs:907:9:
assertion failed: min <= max
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary>Full stacktrace</summary>
<p>

```
thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cmp.rs:907:9:
assertion failed: min <= max
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
   3: core::cmp::Ord::clamp
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cmp.rs:907:9
   4: typst::layout::container::distribute
             at ./crates/typst/src/layout/container.rs:944:23
   5: typst::layout::container::breakable_pod
             at ./crates/typst/src/layout/container.rs:899:32
   6: typst::layout::container::<impl typst::foundations::content::Packed<typst::layout::container::BlockElem>>::layout_multiple
             at ./crates/typst/src/layout/container.rs:592:13
   7: typst::layout::flow::collect::layout_multi_impl::{{closure}}
             at ./crates/typst/src/layout/flow/collect.rs:466:5
   8: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
   9: typst::layout::flow::collect::layout_multi_impl
             at ./crates/typst/src/layout/flow/collect.rs:443:1
  10: typst::layout::flow::collect::MultiChild::layout_full::{{closure}}
             at ./crates/typst/src/layout/flow/collect.rs:427:13
  11: typst::layout::flow::collect::CachedCell<T>::get_or_init
             at ./crates/typst/src/layout/flow/collect.rs:626:22
  12: typst::layout::flow::collect::MultiChild::layout_full
             at ./crates/typst/src/layout/flow/collect.rs:424:9
  13: typst::layout::flow::collect::MultiChild::layout
             at ./crates/typst/src/layout/flow/collect.rs:396:24
  14: typst::layout::flow::distribute::Distributor::multi
             at ./crates/typst/src/layout/flow/distribute.rs:266:30
  15: typst::layout::flow::distribute::Distributor::child
             at ./crates/typst/src/layout/flow/distribute.rs:119:36
  16: typst::layout::flow::distribute::Distributor::run
             at ./crates/typst/src/layout/flow/distribute.rs:98:13
  17: typst::layout::flow::distribute::distribute
             at ./crates/typst/src/layout/flow/distribute.rs:22:24
  18: typst::layout::flow::compose::Composer::column_contents
             at ./crates/typst/src/layout/flow/compose.rs:227:9
  19: typst::layout::flow::compose::Composer::column
             at ./crates/typst/src/layout/flow/compose.rs:180:19
  20: typst::layout::flow::compose::Composer::page_contents
             at ./crates/typst/src/layout/flow/compose.rs:108:20
  21: typst::layout::flow::compose::Composer::page
             at ./crates/typst/src/layout/flow/compose.rs:88:19
  22: typst::layout::flow::compose::compose
             at ./crates/typst/src/layout/flow/compose.rs:38:5
  23: typst::layout::flow::layout_flow
             at ./crates/typst/src/layout/flow/mod.rs:221:21
  24: typst::layout::pages::run::layout_page_run_impl::{{closure}}
             at ./crates/typst/src/layout/pages/run.rs:165:20
  25: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
  26: typst::layout::pages::run::layout_page_run_impl
             at ./crates/typst/src/layout/pages/run.rs:69:1
  27: typst::layout::pages::run::layout_page_run
             at ./crates/typst/src/layout/pages/run.rs:56:5
  28: typst::layout::pages::layout_pages::{{closure}}
             at ./crates/typst/src/layout/pages/mod.rs:107:13
  29: typst::engine::Engine::parallelize::{{closure}}
             at ./crates/typst/src/engine.rs:72:18
  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:272:13
  31: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:305:13
  32: core::option::Option<T>::map
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:1110:29
  33: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/map.rs:108:26
  34: rayon::iter::plumbing::Folder::consume_iter
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:177:21
  35: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  36: rayon::iter::plumbing::Producer::fold_with
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:109:9
  37: rayon::iter::plumbing::bridge_producer_consumer::helper
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:437:13
  38: rayon::iter::plumbing::bridge_producer_consumer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:396:12
  39: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:372:13
  40: <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:147:13
  41: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:83:9
  42: rayon::iter::plumbing::bridge
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:356:12
  43: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::drive
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:71:9
  44: <rayon::iter::map::Map<I,F> as rayon::iter::IndexedParallelIterator>::drive
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:68:9
  45: rayon::iter::collect::collect_into_vec::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/collect/mod.rs:20:46
  46: rayon::iter::collect::collect_with_consumer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/collect/mod.rs:84:18
  47: rayon::iter::collect::collect_into_vec
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/collect/mod.rs:20:5
  48: rayon::iter::IndexedParallelIterator::collect_into_vec
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2535:9
  49: typst::engine::Engine::parallelize
             at ./crates/typst/src/engine.rs:62:9
  50: typst::layout::pages::layout_pages
             at ./crates/typst/src/layout/pages/mod.rs:99:20
  51: typst::layout::pages::layout_document_impl::{{closure}}
             at ./crates/typst/src/layout/pages/mod.rs:82:17
  52: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
  53: typst::layout::pages::layout_document_impl
             at ./crates/typst/src/layout/pages/mod.rs:47:1
  54: typst::layout::pages::layout_document
             at ./crates/typst/src/layout/pages/mod.rs:35:5
  55: typst::compile_impl
             at ./crates/typst/src/lib.rs:154:20
  56: typst::compile
             at ./crates/typst/src/lib.rs:89:18
  57: typst::compile::compile_once
             at ./crates/typst-cli/src/compile.rs:122:39
  58: typst::compile::compile::{{closure}}
             at ./crates/typst-cli/src/compile.rs:104:38
  59: typst::timings::Timer::record
             at ./crates/typst-cli/src/timings.rs:48:23
  60: typst::compile::compile
             at ./crates/typst-cli/src/compile.rs:104:5
  61: typst::dispatch
             at ./crates/typst-cli/src/main.rs:62:38
  62: typst::main
             at ./crates/typst-cli/src/main.rs:47:15
  63: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
```

</p>
</details> 

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This one-liner appears to reproduce the same bug:

```typ
#block(height: -1pt)[]
```

<details><summary>Full stacktrace</summary>
<p>

```
thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cmp.rs:907:9:
assertion failed: min <= max
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
   3: core::cmp::Ord::clamp
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cmp.rs:907:9
   4: typst::layout::container::distribute
             at ./crates/typst/src/layout/container.rs:944:23
   5: typst::layout::container::breakable_pod
             at ./crates/typst/src/layout/container.rs:899:32
   6: typst::layout::container::<impl typst::foundations::content::Packed<typst::layout::container::BlockElem>>::layout_multiple
             at ./crates/typst/src/layout/container.rs:592:13
   7: typst::layout::flow::collect::layout_multi_impl::{{closure}}
             at ./crates/typst/src/layout/flow/collect.rs:466:5
   8: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
   9: typst::layout::flow::collect::layout_multi_impl
             at ./crates/typst/src/layout/flow/collect.rs:443:1
  10: typst::layout::flow::collect::MultiChild::layout_full::{{closure}}
             at ./crates/typst/src/layout/flow/collect.rs:427:13
  11: typst::layout::flow::collect::CachedCell<T>::get_or_init
             at ./crates/typst/src/layout/flow/collect.rs:626:22
  12: typst::layout::flow::collect::MultiChild::layout_full
             at ./crates/typst/src/layout/flow/collect.rs:424:9
  13: typst::layout::flow::collect::MultiChild::layout
             at ./crates/typst/src/layout/flow/collect.rs:396:24
  14: typst::layout::flow::distribute::Distributor::multi
             at ./crates/typst/src/layout/flow/distribute.rs:266:30
  15: typst::layout::flow::distribute::Distributor::child
             at ./crates/typst/src/layout/flow/distribute.rs:119:36
  16: typst::layout::flow::distribute::Distributor::run
             at ./crates/typst/src/layout/flow/distribute.rs:98:13
  17: typst::layout::flow::distribute::distribute
             at ./crates/typst/src/layout/flow/distribute.rs:22:24
  18: typst::layout::flow::compose::Composer::column_contents
             at ./crates/typst/src/layout/flow/compose.rs:227:9
  19: typst::layout::flow::compose::Composer::column
             at ./crates/typst/src/layout/flow/compose.rs:180:19
  20: typst::layout::flow::compose::Composer::page_contents
             at ./crates/typst/src/layout/flow/compose.rs:108:20
  21: typst::layout::flow::compose::Composer::page
             at ./crates/typst/src/layout/flow/compose.rs:88:19
  22: typst::layout::flow::compose::compose
             at ./crates/typst/src/layout/flow/compose.rs:38:5
  23: typst::layout::flow::layout_flow
             at ./crates/typst/src/layout/flow/mod.rs:221:21
  24: typst::layout::pages::run::layout_page_run_impl::{{closure}}
             at ./crates/typst/src/layout/pages/run.rs:165:20
  25: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
  26: typst::layout::pages::run::layout_page_run_impl
             at ./crates/typst/src/layout/pages/run.rs:69:1
  27: typst::layout::pages::run::layout_page_run
             at ./crates/typst/src/layout/pages/run.rs:56:5
  28: typst::layout::pages::layout_pages::{{closure}}
             at ./crates/typst/src/layout/pages/mod.rs:107:13
  29: typst::engine::Engine::parallelize::{{closure}}
             at ./crates/typst/src/engine.rs:72:18
  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:272:13
  31: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:305:13
  32: core::option::Option<T>::map
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:1110:29
  33: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/map.rs:108:26
  34: rayon::iter::plumbing::Folder::consume_iter
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:177:21
  35: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:248:21
  36: rayon::iter::plumbing::Producer::fold_with
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:109:9
  37: rayon::iter::plumbing::bridge_producer_consumer::helper
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:437:13
  38: rayon::iter::plumbing::bridge_producer_consumer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:396:12
  39: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:372:13
  40: <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:147:13
  41: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:83:9
  42: rayon::iter::plumbing::bridge
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:356:12
  43: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::drive
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/vec.rs:71:9
  44: <rayon::iter::map::Map<I,F> as rayon::iter::IndexedParallelIterator>::drive
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map.rs:68:9
  45: rayon::iter::collect::collect_into_vec::{{closure}}
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/collect/mod.rs:20:46
  46: rayon::iter::collect::collect_with_consumer
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/collect/mod.rs:84:18
  47: rayon::iter::collect::collect_into_vec
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/collect/mod.rs:20:5
  48: rayon::iter::IndexedParallelIterator::collect_into_vec
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2535:9
  49: typst::engine::Engine::parallelize
             at ./crates/typst/src/engine.rs:62:9
  50: typst::layout::pages::layout_pages
             at ./crates/typst/src/layout/pages/mod.rs:99:20
  51: typst::layout::pages::layout_document_impl::{{closure}}
             at ./crates/typst/src/layout/pages/mod.rs:82:17
  52: comemo::cache::memoized
             at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comemo-0.4.0/src/cache.rs:61:18
  53: typst::layout::pages::layout_document_impl
             at ./crates/typst/src/layout/pages/mod.rs:47:1
  54: typst::layout::pages::layout_document
             at ./crates/typst/src/layout/pages/mod.rs:35:5
  55: typst::compile_impl
             at ./crates/typst/src/lib.rs:154:20
  56: typst::compile
             at ./crates/typst/src/lib.rs:89:18
  57: typst::compile::compile_once
             at ./crates/typst-cli/src/compile.rs:122:39
  58: typst::compile::compile::{{closure}}
             at ./crates/typst-cli/src/compile.rs:104:38
  59: typst::timings::Timer::record
             at ./crates/typst-cli/src/timings.rs:48:23
  60: typst::compile::compile
             at ./crates/typst-cli/src/compile.rs:104:5
  61: typst::dispatch
             at ./crates/typst-cli/src/main.rs:62:38
  62: typst::main
             at ./crates/typst-cli/src/main.rs:47:15
  63: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by shadmanZero** [comment]
issue is coming from relative_to it is making negative number we need to use result.max(T::zero()) for it

**Comment by laurmaedje** [comment]
Crazy that not a single test caught this.

**Comment by rbruenig** [comment]
I am having the same problem. Is there a workaround?

**Comment by laurmaedje** [comment]
Could you show a small snippet that causes the problem for you?

**Comment by rbruenig** [comment]
@laurmaedje This is in a fairly large document, but we were able to track it down using the hint from @PgBiel . We had a block with negative relative height:
```
#align(start + horizon, block(
  ... snip ...
  place((top + left),
       ... snip ...
        block(  
                width: 1%,
                height: -7%,
                inset: (x: 70pt),
                outset: (y: 1pt),
        ) +
     ... snip ...
  )
))
```
We were able to fix it by changing the different sizes and alignments so that negative values were not needed anymore.

**Comment by PgBiel** [comment]
Found a similar problem:

```typ
#set text(-1pt)

abc
```

Regressed with a panic on 0.12. Same reason (clamp), but elsewhere in flow code.
