### ISSUE TITLE
Panic when measuring unbounded spacing

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#5263]
### Description

Not a regression, this also panics in 0.11.1.

```typ
#context measure(layout(bounds => h(bounds.width)))
```

```
thread 'main' panicked at crates\typst\src\layout\inline\line.rs:549:22:
assertion failed: size.is_finite()
```

Same issue in math for another panic location:

```typ
#show math.equation.where(number-align: horizon + end): it => {
  // Prevent recursion.
  let eq = math.equation.with(block: true, number-align: start)

  let w = measure(eq(it)).width
  layout(bounds => eq(it + h(bounds.width)))
}

$ a + #block[$ a $] $
```

```
thread 'main' panicked at crates\typst\src\math\fragment.rs:184:18:
assertion failed: size.is_finite()
```

Replacing the `h(...)` with e.g. a `box(width: ...)` gets rid of the panic.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
Slightly simpler reproduction for the first case:
```typ
#context measure(h(calc.inf * 1pt))
```

**Comment by olligobber** [comment]
This is also effecting use of the wrap-it package in typst 0.13.1:
```typ
#import "@preview/wrap-it:0.1.1": wrap-content
#wrap-content(box(inset: (bottom: 100%))[a], [b])
```
leads to the error:
```
thread 'main' panicked at crates/typst-layout/src/inline/line.rs:555:22:
assertion failed: size.is_finite()
```
which is the same error I get for the above examples.
